name: peivate-npm-publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=sarasafreelancer@gmail.com
            //verdaccio.amtek.com/:_authToken=$NODE_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NODE_TOKEN }}
      - run: npm publish
