name: peivate-npm-publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=sarasafreelancer@gmail.com
            //verdaccio.amtek.com/:_authToken=$NODE_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GI_TOKEN }}
