name: peivate-npm-publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: 'http://verdaccio.amtek.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_TOKEN }}